In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
#Get dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [10]:
#Get Shape of array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
#Get Type of array
print(a.dtype)
print(b.dtype)

int32
int32


In [14]:
#Get size of array
print(a.itemsize)
print(b.itemsize)

4
4


# Changing specific elements, row, columns etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [19]:
#gives specific element where indexing starts from 0
a[1,5]


13

In [20]:
#Get specific row
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#Get specific columns
a[:,0]

array([1, 8])

In [26]:
#we can assign different value for specific indexes
a[1,5] = 2000
print(a)

[[   1    2    3    4    5    6    7]
 [   8    9   10   11   12 2000   14]]


# Initializing different types of arrays

In [27]:
#All zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [35]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [36]:
np.full((3,4),76)

array([[76, 76, 76, 76],
       [76, 76, 76, 76],
       [76, 76, 76, 76]])

In [37]:
#Random decimal number
np.random.rand(3,4)

array([[0.14324591, 0.90405378, 0.80170348, 0.12627844],
       [0.65624852, 0.8109369 , 0.46072858, 0.49631255],
       [0.83996487, 0.18069077, 0.10233407, 0.00508557]])

In [41]:
#Random integer number
np.random.randint(7,size=(3,4)) #it gives random integer upto 7

array([[1, 3, 2, 1],
       [4, 1, 4, 2],
       [3, 3, 5, 2]])

In [44]:
np.random.randint(2,7,size=(3,4)) #it gives random integer between 2 and 7 where 7 is exclusive

array([[2, 3, 2, 5],
       [5, 2, 3, 6],
       [2, 3, 6, 4]])

In [47]:
#get identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
arr = np.array([[1,2,3]])
re = np.repeat(arr,4,axis=0)
re

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [62]:
#creating 5*5 matrix where outer is 1 inner is 0 and middle is 9
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
a = np.array([1,2,3])
b = a.copy() #this function is used so that value of a is not changed when b changes
b[0] = 5
print(a)

[1 2 3]


# Mathematics

In [65]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [66]:
a-2

array([-1,  0,  1])

In [67]:
a+2

array([3, 4, 5])

In [68]:
a*2

array([2, 4, 6])

In [69]:
a/2

array([0.5, 1. , 1.5])

In [71]:
b = np.array([1,1,1])
a+b

array([2, 3, 4])

# Linear Algebra

In [74]:
#row of one matrices should be equal to the column of another matrics while multiplying 
#similarly goes for addition and substraction
a = np.ones((2,3))
print(a)
b = np.full((3,2),3)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

# Statistics

In [78]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [79]:
np.min(stats)

1

In [80]:
np.max(stats)

6

In [82]:
np.max(stats,axis=1)

array([3, 6])

# Reorganizing Arrays

In [84]:
arr = np.ones((3,4))*5
print(arr)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [86]:
arr.reshape(6,2) #mismatch between number of element and reshape element wont work

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [88]:
arr2 = np.ones((3,4))*3
print(arr2)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [90]:
#vertical stack
np.vstack([arr,arr2])

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [91]:
#horizontal stack
np.hstack([arr,arr2])

array([[5., 5., 5., 5., 3., 3., 3., 3.],
       [5., 5., 5., 5., 3., 3., 3., 3.],
       [5., 5., 5., 5., 3., 3., 3., 3.]])


# Loading data

In [97]:
file = np.genfromtxt('data.txt',delimiter=' ')
file

array([ 1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 12., 13., 14., 15., 16.])

Boolean Masking and advance indexing

In [98]:
file>4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])